### ISSUE TITLE
[BUG] - Menu & burger menu not displaying ok over leaflet map

### ISSUE THREAD

**Issue by alexstan67** [alexstan67/wef_2023#63]
**Describe the bug**
The leaflet elements are using high z-index values, example:
````css
// vendor/assets/stylesheets/leaflet.css
.leaflet-bottom {
	position: absolute;
	z-index: 1000;
	pointer-events: none;
	}
````
Therefore, we need to modify the `z-index` value of following css properties:
burger-menu-content => 1100
account-menu-content => 1100
